/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-03-25 11:24:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.json.simple.*;
import java.util.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <a class=\"close-reveal-modal\">&#215;</a>\n");
      out.write("    \n");
      out.write("    <div class=\"large-12 small-12 columns\">\n");
      out.write(" \n");
      out.write(" \t");
 
 		String GetindivialString = request.getParameter("detail");
	    String getURl = (String) application.getAttribute("getDomain");
 		Object obj=JSONValue.parse(GetindivialString);
  	 	JSONObject getobj=(JSONObject)obj;

 	
      out.write("\n");
      out.write("      <div class=\"row\" id=\"");
      out.print(getobj.get("id") );
      out.write("\">\n");
      out.write(" \n");
      out.write("  <!-- Side Bar -->\n");
      out.write("\n");
      out.write("        <div class=\"large-4 small-12 columns\">\n");
      out.write(" \n");
      out.write("          <img src=\"");
      out.print(getURl);
      out.write("\\img\\");
      out.print(getobj.get("img") );
      out.write("\">\n");
      out.write(" \t\t\t<div class=\"row\">\t\t\n");
      out.write("          \t\t<div class=\"large-12 small-12 columns\">\n");
      out.write("      \t\t\t\t\t\t<div class=\"row\">\n");
      out.write("       \t\t\t\t\t\t\t <div class=\"small-3 columns\">\n");
      out.write("          \t\t\t\t\t\t \t<label for=\"left-label\" class=\"left inline\">Rating:</label>\n");
      out.write("        \t\t\t\t\t\t </div>\n");
      out.write("        \t\t\t\t\t\t <div class=\"small-6 columns\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select id=\"rating\">\n");
      out.write("          \t\t\t\t\t\t\t\t<option value=\"1\">1</option>\n");
      out.write("          \t\t\t\t\t\t\t\t<option value=\"2\">2</option>\n");
      out.write("          \t\t\t\t\t\t\t\t<option value=\"3\">3</option>\n");
      out.write("          \t\t\t\t\t\t\t\t<option value=\"4\">4</option>\n");
      out.write("          \t\t\t\t\t\t\t\t<option value=\"5\">5</option>\n");
      out.write("        \t\t\t\t\t\t\t\t</select>\t\t\t\t\t\t        \n");
      out.write("        \t\t\t\t\t\t</div>\n");
      out.write("        \t\t\t\t\t\t <div class=\"small-3 columns\">\n");
      out.write("         \t\t\t\t\t\t <a id=\"rSubmit\"  class=\"button postfix\"><small>Submit</small></a>\n");
      out.write("       \t\t\t\t\t\t\t </div>\n");
      out.write("\t\t\t\t\t\t      </div>      \n");
      out.write("          \t\t</div>\n");
      out.write(" \t\t\t</div>\n");
      out.write(" \t\t\t\n");
      out.write(" \t\t\t <div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"large-12 small-12 columns\">\n");
      out.write("          \t\t   <h5><small>Average Ratings: 0</small></h5>\n");
      out.write("          \t\t   <h5><small>Total No of Ratings: 0</small></h5>\n");
      out.write("        \t\t   </div>\t\t\t\t\t\t      \n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t    <div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"large-12 small-12 columns\">\n");
      out.write("          \t\t   <div class=\"panel\">\n");
      out.write("  \t\t\t\t\t<ul class=\"disc\">\n");
      out.write("  \t\t\t\t\t\t\t<li>Rate 5: 0</li>\n");
      out.write("  \t\t\t\t\t\t\t<li>Rate 4: 0</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Rate 3: 0</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Rate 2: 0</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Rate 1: 0</li>\n");
      out.write(" \t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("        \t\t   </div>\t\t\t\t\t\t      \n");
      out.write("\t\t\t    </div>\n");
      out.write("       </div>\n");
      out.write(" \n");
      out.write("    <!-- End Side Bar -->\n");
      out.write(" \n");
      out.write(" \n");
      out.write("    <!-- Thumbnails -->\n");
      out.write(" \n");
      out.write("        <div class=\"large-8  columns\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            \t<div class=\"large-12 hide-for-small columns\">\n");
      out.write("            \t    <ul class=\"pricing-table\">\n");
      out.write("  \t\t\t\t\t\t<li class=\"title\">");
      out.print(getobj.get("name") );
      out.write("</li>\n");
      out.write("  \t\t\t\t\t\t<li class=\"price\">");
      out.print(getobj.get("price") );
      out.write("</li>\n");
      out.write("  \t\t\t\t\t\t<li class=\"bullet-item\">Color: ");
      out.print(getobj.get("color"));
      out.write("</li>\n");
      out.write("  \t\t\t\t\t\t<li class=\"bullet-item\">OS: ");
      out.print(getobj.get("os"));
      out.write("</li>\n");
      out.write("  \t\t\t\t\t\t<li class=\"bullet-item\">Processor: ");
      out.print(getobj.get("processor"));
      out.write("</li>\n");
      out.write("  \t\t\t\t\t\t<li class=\"bullet-item\">Momery: ");
      out.print(getobj.get("momery"));
      out.write("</li>\n");
      out.write(" \t\t\t\t\t\t<li class=\"bullet-item\">Storage: ");
      out.print(getobj.get("storage"));
      out.write("</li>  \n");
      out.write("\t\t\t\t\t</ul>        \n");
      out.write("            \t</div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write(" \n");
      out.write("    <!-- End Thumbnails -->\n");
      out.write(" \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("    </div>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
