/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-03-18 14:08:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1395151525000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1395136722000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("\n");
      out.write("\t<title>COMP5347 Assignment 1</title>\n");
      out.write("\t<!-- If you are using CSS version, only link these 2 files, you may add app.css to use for your overrides if you like. -->\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"css/normalize.css\">\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"css/foundation.min.css\">\n");
      out.write("\n");
      out.write("  \t<script src=\"js/vendor/jquery.js\"></script>\n");
      out.write("  \t<script src=\"js/vendor/modernizr.js\"></script>\n");
      out.write("  \t<script src=\"js/foundation/foundation.js\"></script>\n");
      out.write("  \t<script src=\"js/foundation/foundation.dropdown.js\"></script>\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("  \t\n");
      out.write("\t\n");
      out.write("\t<!--[if lt IE 9]>\n");
      out.write("\t<script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("\t<![endif]-->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("    <div class=\"large-12 columns\">\n");
      out.write(" \n");
      out.write("    <!-- Navigation -->\n");
      out.write(" \n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"large-12 columns\">\n");
      out.write(" \n");
      out.write("          <nav class=\"top-bar\" data-topbar>\n");
      out.write("            <ul class=\"title-area\">\n");
      out.write("              <!-- Title Area -->\n");
      out.write("              <li class=\"name\">\n");
      out.write("                <h1>\n");
      out.write("                  <a href=\"#\">\n");
      out.write("                    COMP5347 Assignment 1\n");
      out.write("                  </a>\n");
      out.write("                </h1>\n");
      out.write("              </li>\n");
      out.write("             <li class=\"toggle-topbar menu-icon\"><a href=\"#\"><span>menu</span></a></li>\n");
      out.write("              \n");
      out.write("            </ul>\n");
      out.write("         \n");
      out.write("            <section class=\"top-bar-section\">\n");
      out.write("              <!-- Right Nav Section -->\n");
      out.write("              <ul class=\"right\">\n");
      out.write("              \t<li class=\"divider\"></li>\n");
      out.write("                \n");
      out.write("                <li>\n");
      out.write("                  <a href=\"#\" data-dropdown=\"drop1\">No user login</a>\n");
      out.write("                  <ul id=\"drop1\" class=\"f-dropdown\" data-dropdown-content>\n");
      out.write("                    <li><a href=\"#\">Dropdown Option</a></li>\n");
      out.write("                    <li><a href=\"#\">Dropdown Option</a></li>\n");
      out.write("                    <li><a href=\"#\">Dropdown Option</a></li>\n");
      out.write("                    <li class=\"divider\"></li>\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("              \n");
      out.write("            \n");
      out.write("              </ul>\n");
      out.write("            </section>\n");
      out.write("          </nav>\n");
      out.write("          <!-- End Top Bar -->\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write(" \n");
      out.write("    <!-- End Navigation -->\n");
      out.write(" \n");
      out.write("      <div class=\"row\">\n");
      out.write(" \n");
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("    <!-- Thumbnails -->\n");
      out.write(" \n");
      out.write("        <div class=\"large-12 columns\">\n");
      out.write("          <div class=\"row\">\n");
      out.write(" \n");
      out.write("            <div class=\"large-4 small-6 columns\">\n");
      out.write("              <img src=\"http://placehold.it/1000x1000&text=Thumbnail\">\n");
      out.write(" \n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <h5>Item Name</h5>\n");
      out.write("                <h6 class=\"subheader\">$000.00</h6>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write(" \n");
      out.write("            <div class=\"large-4 small-6 columns\">\n");
      out.write("              <img src=\"http://placehold.it/500x500&text=Thumbnail\">\n");
      out.write(" \n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <h5>Item Name</h5>\n");
      out.write("                <h6 class=\"subheader\">$000.00</h6>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write(" \n");
      out.write("            <div class=\"large-4 small-6 columns\">\n");
      out.write("              <img src=\"http://placehold.it/500x500&text=Thumbnail\">\n");
      out.write(" \n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <h5>Item Name</h5>\n");
      out.write("                <h6 class=\"subheader\">$000.00</h6>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write(" \n");
      out.write("            <div class=\"large-4 small-6 columns\">\n");
      out.write("              <img src=\"http://placehold.it/500x500&text=Thumbnail\">\n");
      out.write(" \n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <h5>Item Name</h5>\n");
      out.write("                <h6 class=\"subheader\">$000.00</h6>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write(" \n");
      out.write("            <div class=\"large-4 small-6 columns\">\n");
      out.write("              <img src=\"http://placehold.it/500x500&text=Thumbnail\">\n");
      out.write(" \n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <h5>Item Name</h5>\n");
      out.write("                <h6 class=\"subheader\">$000.00</h6>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write(" \n");
      out.write("            <div class=\"large-4 small-6 columns\">\n");
      out.write("              <img src=\"http://placehold.it/500x500&text=Thumbnail\">\n");
      out.write(" \n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <h5>Item Name</h5>\n");
      out.write("                <h6 class=\"subheader\">$000.00</h6>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write(" \n");
      out.write("    <!-- End Thumbnails -->\n");
      out.write(" \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("    <!-- Footer -->\n");
      out.write(" \n");
      out.write("      <footer class=\"row\">\n");
      out.write("        <div class=\"large-12 columns\"><hr />\n");
      out.write("          <div class=\"row\">\n");
      out.write(" \n");
      out.write("              <p class=\"text-center\">@The Demo processed by XUN ZHAO (440042783)</p>\n");
      out.write(" \n");
      out.write("            \n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </footer>\n");
      out.write(" \n");
      out.write("    <!-- End Footer -->\n");
      out.write(" \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
